services:
  mysql:
    image: mysql:8.1   # Versión fija y soportada por Flyway
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"   # Mapea explícitamente el puerto 3306 del contenedor al 3306 de tu PC
