on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, synchronize, reopened]

name: CI - Kotlin + SonarCloud

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'


      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: SonarCloud Scan (Action with pinned SHA)
        uses: SonarSource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9 # v5.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
naming:
  TestFunctionNaming:
    active: true
    # Permite nombres con backticks
    functionPattern: '^([a-z][a-zA-Z0-9]*|`.*`)$'
  FunctionNaming:
    ignoreAnnotated:
      - 'Test'



